# Generated by Django 3.0.6 on 2020-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='address',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
